package controller;

public enum Commands {
	REMOVE_USER,
	C_LOG_IN,
<<<<<<< HEAD
	RETURN_LOG_IN,
	RETURN_PANEL_1,
	RETURN_PANEL_2,
	RETURN_PANEL_4,
=======
	AC_SAVE_CHANGES_BUTTON,
	AC_SEARCH_BY_WORDS,
	
>>>>>>> branch 'master' of https://github.com/EmersonUrielVargas/AssistantSchool_cliente.git
	AC_SHOW_NOTES_BUTTON,
	AC_SHOW_COMMENTS_BUTTON,
	AC_SAVE_COMMENTS_BUTTON,
	AC_SHOW_REPORT_BUTTON,
	AC_SHOW_COURSES_BUTTON,
	AC_SHOW_TEACHERS_BUTTON,
	AC_SHOW_STUDENTS_BUTTON,
	AC_SHOW_SUBJECTS_BUTTON,
	AC_SHOW_LOGOUT_BUTTON,
	AC_SHOW_REGISTER_BUTTON,
	ADD_CLIENT,
	REGISTER_CLIENT,
	ADD_COURSE,
	ADD_SUBJECT,
	ASIG_SUBJECT_TEACHER,
	ASIG_COURSE_TEACHER,
	SEE_SUBJECTS,
	REGISTER_COURSE,
	REGISTER_SUBJECT,
	ASIG_SUBJECT,
	ASIG_SUBJECT_TO_COURSE,
	ADD_SUBJECT_TO_COURSE,
	RETURN_PANEL_3,
	ASIG_COURSE,
	SEE_COURSES,
	AC_SAVE_CHANGES_BUTTON,
	
}
